language: crystal
os:
- linux

script:
  - crystal spec
  - crystal spec -Dpreview_mt
  - crystal tool format --check
  - shards build
  - crystal docs

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs
